#ifndef Enum_h__
#define Enum_h__

enum RESOURCEID { RESOURCE_STATIC, RESOURCE_LOGO, RESOURCE_STAGE, RESOURCE_END };
enum LOADINGID  { LOADING_STAGE, LOADING_BOSS, LOADING_END };
enum SKILLID	{ SKILL_FIRE, SKILL_WIND, SKILL_ICE, SKILL_EARTH, SKILL_END };
enum WALLPOSITION { WALL_LEFT, WALL_TOP, WALL_RIGHT, WALL_BOTTOM, WALL_CEILING, WALL_END };

#endif // Enum_h__
